<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.AspNetCore" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UBP.Result\UBP.Result.csproj" />
    <ProjectReference Include="..\UBP.IAM.Persistence\UBP.IAM.Persistence.csproj" />
    <ProjectReference Include="..\..\UBP.CQRS\UBP.CQRS.csproj" />
  </ItemGroup>

</Project>
