<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../UBP.Core/UBP.Core.Persistence.EF.PostgreSQL/UBP.Core.Persistence.EF.PostgreSQL.csproj" />
    <ProjectReference Include="..\..\UBP.Core\UBP.Core.Data.EF\UBP.Core.Data.EF.csproj" />
    <ProjectReference Include="..\UBP.Storage.Domain\UBP.Storage.Domain.csproj" />
  </ItemGroup>

</Project>
