<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UBP.Core.Domain\UBP.Core.Domain.csproj" />
    <ProjectReference Include="..\UBP.Core.Persistence.EF\UBP.Core.Persistence.EF.csproj" />
  </ItemGroup>

</Project>
